### PR TITLE
chore: add makefile to simplify dev workflow

### PR DESCRIPTION
**Pull request by Extheoisah**

### CODE REVIEW

**Review by Emmanuel-Develops — COMMENTED** [review]
Looks good!
Has it been tested?

**Comment by Extheoisah** [comment]
> Looks good! Has it been tested?

Yes. Works locally for me. You can test the code locally too.

**Review by Emmanuel-Develops — CHANGES_REQUESTED** [review]
Works good.
One issue is the .env.example `DB_URL` isn't accurate.
Here is the incorrect value
`DB_URL=postgres://postgres:postgres@localhost:5432/postgres`
Here's the accurate value 
`DB_URL=postgres://postgres:postgress@localhost:5432/postgres`

It is missing a second `s` in `'postgress'` before `'@localhost'`

This happens if you run `cp .env.example .env`, we usually just copy and paste the env so it mostly went unnoticed

**Comment by Extheoisah** [comment]
> chore: address pr comment

fixed here https://github.com/bitcointranscripts/transcription-review-backend/pull/48/commits/04ab540f90b59cc92e5043a847e7bf47327ae8db

**Review by Emmanuel-Develops — APPROVED** [review]

**Pull request merged**
