### PR TITLE
feat: convert project to ts

### PR DESCRIPTION
**Pull request by Extheoisah**
Edit: PR is ready and all routes should work. I've tested locally but I'd like extra testing before getting this in.

### CODE REVIEW

**Comment by Extheoisah** [comment]
Todo! currently the associations between models is broken and I don't have a fix for it yet.
if you try to retrieve reviews by id, you get this error `EagerLoadingError [SequelizeEagerLoadingError]: transcript is not associated to review!`
my understanding is that the model associations are not initialised and saved properly, like it gets recreated every time.

**Comment by BalogunofAfrica** [comment]
Nice work, interested in this. Especially also adding some runtime type validation too for things like the incoming requests.

Let me know how I can help with this

**Comment by Extheoisah** [comment]
> Nice work, interested in this. Especially also adding some runtime type validation too for things like the incoming requests.
> 
> Let me know how I can help with this

You can start by getting it run locally first. I need to fix the conflicts but that is trivial. Currently the associations between models is broken and I don't have a fix for it yet. If you want to have a look at that, it'll be helpful.

**Review by nully0x — APPROVED** [review]
LGTM

**Pull request merged**
